name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "master"
  workflow_call:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"
          cache: true

      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Display Coverage in CLI
        run: go tool cover -func=coverage.out

      - name: Generate Job Summary
        run: |
          echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          
          echo "| File | Line | Function | Coverage |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          
          go tool cover -func=coverage.out | \
          grep -v "total:" | \
          awk '{ 
            split($1, a, ":"); 
            print "| " a[1] " | " a[2] " | " $2 " | " $3 " |" 
          }' >> $GITHUB_STEP_SUMMARY
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Total Coverage" >> $GITHUB_STEP_SUMMARY
          TOTAL=$(go tool cover -func=coverage.out | grep "total:" | awk '{print $3}')
          echo "**$TOTAL**" >> $GITHUB_STEP_SUMMARY

  verify-docker:
    name: Verify Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (Dry Run)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          target: final
          tags: verify-build:latest
