name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "master"
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"
          cache: true

      # - name: Run Tests (Unit + Integration)
      #   if: github.actor == github.repository_owner
      #   env:
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #   run: go test -v -tags=integration -coverprofile=coverage.out ./...

      # - name: Run Tests (Unit Only)
      #   if: github.actor != github.repository_owner
      #   run: go test -v -coverprofile=coverage.out ./...

      - name: Run Tests & Generate Coverage
        id: coverage
        uses: gwatts/go-coverage-action@v2
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOFLAGS: ${{ github.actor == github.repository_owner && '-tags=integration' || '' }}
        with:
          coverage-threshold: 95

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ steps.coverage.outputs.report-pathname }}
          path: coverage.html
          retention-days: 7

  verify-docker:
    name: Verify Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (Dry Run)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          target: final
          tags: verify-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
